--Override Card.RegisterEffect
Duel.LoadScript("_register_effect.lua")
--Custom Utility
Duel.LoadScript("CustomType.lua")
Duel.LoadScript("init_Crowel.lua")
Duel.LoadScript("init_kaos.lua")
Duel.LoadScript("init_Spinel.lua")
Duel.LoadScript("init_Sanso.lua")
--Convert from Core (to be removed)
Duel.LoadScript("z1_core_constant.lua")
Duel.LoadScript("z1_core_proc_fusion.lua")
Duel.LoadScript("z1_core_proc_ritual.lua")
Duel.LoadScript("z1_core_utility.lua")
--Custom Summon Types
Duel.LoadScript("z2_proc_beyond.lua")
Duel.LoadScript("z2_proc_delight.lua")
Duel.LoadScript("z2_proc_equation.lua")
Duel.LoadScript("z2_proc_module.lua")
Duel.LoadScript("z2_proc_order.lua")
--To be removed
Duel.LoadScript("z3_OriCS_proc_fusion.lua")
Duel.LoadScript("z3_OriCS_proc_link.lua")
Duel.LoadScript("z3_OriCS_proc_ritual.lua")
Duel.LoadScript("z3_OriCS_proc_synchro.lua")
Duel.LoadScript("z3_OriCS_proc_xyz.lua")
